name: 💡 功能建议
description: 为这个项目提出新的想法
title: "[功能建议]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出时间提出新功能建议！
        请确保填写以下所有部分。
  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 清晰简洁地描述您想要实现的功能。
      placeholder: "我希望能够..."
    validations:
      required: true
  - type: textarea
    id: problem-solution
    attributes:
      label: 问题和解决方案
      description: 描述您试图解决的问题，以及这个功能将如何帮助解决。
      placeholder: "目前，当我尝试..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 考虑过的替代方案
      description: 描述您考虑过的任何替代解决方案或功能。
      placeholder: "我考虑过..."
  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 这个功能对您来说有多重要？
      options:
        - 高（对我的工作流程至关重要）
        - 中（会很有帮助）
        - 低（有更好）
    validations:
      required: true
  - type: dropdown
    id: impact
    attributes:
      label: 影响范围
      description: 有多少用户会从这个功能中受益？
      options:
        - 所有用户
        - 大多数用户
        - 部分用户
        - 仅我个人
    validations:
      required: true
  - type: textarea
    id: technical-details
    attributes:
      label: 技术细节
      description: 您想分享的任何技术考虑或实现细节。
      placeholder: "这个功能可以通过..."
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果适用，添加截图以帮助解释您的功能建议。
      placeholder: "您可以在此处拖放截图..."
  - type: checkboxes
    id: terms
    attributes:
      label: 行为准则
      description: 提交此问题即表示您同意遵守本项目的行为准则
      options:
        - label: 我同意遵守本项目的行为准则
          required: true 