name: ❓ 讨论 & 提问 (中文)
description: 寻求帮助、讨论问题、提出疑问等...
title: '[讨论]: '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        感谢您的提问！请尽可能详细地描述您的问题，这样我们才能更好地帮助您。

  - type: checkboxes
    id: checklist
    attributes:
      label: Issue 检查清单
      description: |
        在提交 Issue 前请确保您已经完成了以下所有步骤
      options:
        - label: 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
          required: true
        - label: 我确认自己需要的是提出问题并且讨论问题，而不是 Bug 反馈或需求建议。
          required: true
        - label: 我已阅读 [Github Issues](https://github.com/yeongpin/cursor-free-vip/issues) 并搜索了现有的 [开放 Issue](https://github.com/yeongpin/cursor-free-vip/issues) 和 [已关闭 Issue](https://github.com/yeongpin/cursor-free-vip/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
          required: true
          
  - type: dropdown
    id: platform
    attributes:
      label: 平台
      description: 您正在使用哪个平台？
      options:
        - Windows x32
        - Windows x64
        - macOS Intel
        - macOS ARM64
        - Linux x64
        - Linux ARM64
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 版本
      description: 您正在运行的 Cursor Free Vip 版本是什么？
      placeholder: 例如 v1.0.0
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 您的问题
      description: 请详细描述您的问题
      placeholder: 请尽可能清楚地说明您的问题...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 任何其他相关的信息、截图或代码示例
      render: shell

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 这个问题对您来说有多紧急？
      options:
        - 低 (有空再看)
        - 中 (希望尽快得到答复)
        - 高 (阻碍工作进行)
    validations:
      required: true